name: xingyu-web

services:
  site:
    image: shabox/xingyu-web:latest
    build: .
    restart: always
    ports:
      - "127.0.0.1:3010:3000"
    environment:
      - TZ=Asia/Shanghai
    env_file:
      - .env
    volumes:
      - ./server/data:/app/server/data
    networks:
      default: {}
      web-network:
        aliases:
          - xingyu-web

networks:
  web-network:
    external: true
