name: xingyu-web

services:
  site:
    image: shabox/xingyu-web:latest
    build: .
    container_name: xingyu-web
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    env_file:
      - .env
    volumes:
      - ./server/data:/app/server/data
    networks:
      default: {}
      npm-net:
        aliases:
          - xingyu-web

networks:
  npm-net:
    external: true
    name: nginx-proxy-manager_npm-net
